import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:google_fonts/google_fonts.dart';
void main(){
  runApp(MaterialApp(home: scrolling(),));
}
class scrolling extends StatelessWidget {
  const scrolling({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("SingleScroll"),),
      body: Column(
        children: [
          Center(child: Text("Cindrella",style: GoogleFonts.cabinCondensed(color: Colors.red,fontSize: 30),)),
          Expanded(
            child: SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                height: 500,
                width: double.infinity,
                child: const Text("""Samantha "Sam" Montgomery is raised by her widowed father Hal, who runs a diner in the San Fernando Valley. Hal later dies in the 1994 Northridge earthquake apparently without leaving a will, leading Sam's vain and greedy stepmother Fiona to inherit everything. Eight years later, 17-year-old Sam is tormented by Fiona and her twin daughters/step-sisters Brianna and Gabriella, while the community faces a drought. Sam and her best friend Carter, an aspiring actor, are bullied by the popular clique at school, led by head cheerleader Shelby. Forced to work at the diner to save money to attend Princeton, Sam is looked after by longtime manager Rhonda, and confides in her online pen pal "Nomad", who shares her dream to attend Princeton to become a writer. Unbeknownst to Sam, "Nomad" is Austin Ames, the popular but unhappy school quarterback and Shelby’s boyfriend, whose father expects him to attend the University of Southern California.
          
          Sam agrees to meet "Nomad" at the school Halloween dance, and Austin breaks up with Shelby. Fiona refuses to give Sam the night off to attend the dance, but Rhonda and Carter intervene, and Rhonda gives Sam a mask and wedding dress to wear as "Cinderella". Dressed as "Prince Charming", Austin reveals to Sam that he is "Nomad" but does not recognize her under her mask, and they share a romantic dance. A masked Carter makes out with Shelby after defending her from the unwanted advances of Austin’s friend, but is forced to drive Sam back to the diner before Fiona discovers she is gone. As they leave, Sam drops her cell phone, which is found by Austin, as he and the missing Cinderella are named homecoming prince and princess. The diner staff stall Fiona and her daughters, and Sam arrives just in time, thankfully avoiding having Fiona come into the kitchen to confront her as she was still wearing the dress under her normal clothes.
          
          The next day, Austin covers the school in flyers, hoping to identify the mysterious Cinderella, and Carter is cruelly rejected by Shelby. Austin’s friends present him with a crowd of girls claiming to be Cinderella, without success. He is accepted to Princeton but unable to tell his father, and visits the diner, where Sam tries to tell him the truth. Brianna and Gabriella discover Sam’s emails with Austin, realizing she is the mystery homecoming princess. After failing to convince Austin that they are each Cinderella, the twins present the emails to Shelby, convincing her that Sam schemed to steal Austin away from her. At the school pep rally, Shelby and the twins perform a humiliating skit exposing Sam as Cinderella, and she goes home in tears.
          
          Having intercepted Sam’s acceptance letter from Princeton, Fiona forges a rejection and feigns sympathy, telling Sam she has a job at the diner for life. Rhonda encourages Sam not to lose hope, and her stepsisters inadvertently uncover a wallpapered-over mural of Hal’s motto. Inspired, Sam finally stands up to Fiona and quits the diner, leading Rhonda, the rest of the staff, and even the customers to leave as well. Moving in with Rhonda, Sam confronts Austin for being afraid to show who he really is, just before the homecoming game. Seeing her leaving before the final play of the game, Austin stands up to his father and runs after Sam. He apologizes, and they share their first kiss in the rain as the drought suddenly ends.Samantha "Sam" Montgomery is raised by her widowed father Hal, who runs a diner in the San Fernando Valley. Hal later dies in the 1994 Northridge earthquake apparently without leaving a will, leading Sam's vain and greedy stepmother Fiona to inherit everything. Eight years later, 17-year-old Sam is tormented by Fiona and her twin daughters/step-sisters Brianna and Gabriella, while the community faces a drought. Sam and her best friend Carter, an aspiring actor, are bullied by the popular clique at school, led by head cheerleader Shelby. Forced to work at the diner to save money to attend Princeton, Sam is looked after by longtime manager Rhonda, and confides in her online pen pal "Nomad", who shares her dream to attend Princeton to become a writer. Unbeknownst to Sam, "Nomad" is Austin Ames, the popular but unhappy school quarterback and Shelby’s boyfriend, whose father expects him to attend the University of Southern California.
          
          Sam agrees to meet "Nomad" at the school Halloween dance, and Austin breaks up with Shelby. Fiona refuses to give Sam the night off to attend the dance, but Rhonda and Carter intervene, and Rhonda gives Sam a mask and wedding dress to wear as "Cinderella". Dressed as "Prince Charming", Austin reveals to Sam that he is "Nomad" but does not recognize her under her mask, and they share a romantic dance. A masked Carter makes out with Shelby after defending her from the unwanted advances of Austin’s friend, but is forced to drive Sam back to the diner before Fiona discovers she is gone. As they leave, Sam drops her cell phone, which is found by Austin, as he and the missing Cinderella are named homecoming prince and princess. The diner staff stall Fiona and her daughters, and Sam arrives just in time, thankfully avoiding having Fiona come into the kitchen to confront her as she was still wearing the dress under her normal clothes.
          
          The next day, Austin covers the school in flyers, hoping to identify the mysterious Cinderella, and Carter is cruelly rejected by Shelby. Austin’s friends present him with a crowd of girls claiming to be Cinderella, without success. He is accepted to Princeton but unable to tell his father, and visits the diner, where Sam tries to tell him the truth. Brianna and Gabriella discover Sam’s emails with Austin, realizing she is the mystery homecoming princess. After failing to convince Austin that they are each Cinderella, the twins present the emails to Shelby, convincing her that Sam schemed to steal Austin away from her. At the school pep rally, Shelby and the twins perform a humiliating skit exposing Sam as Cinderella, and she goes home in tears.
          
          Having intercepted Sam’s acceptance letter from Princeton, Fiona forges a rejection and feigns sympathy, telling Sam she has a job at the diner for life. Rhonda encourages Sam not to lose hope, and her stepsisters inadvertently uncover a wallpapered-over mural of Hal’s motto. Inspired, Sam finally stands up to Fiona and quits the diner, leading Rhonda, the rest of the staff, and even the customers to leave as well. Moving in with Rhonda, Sam confronts Austin for being afraid to show who he really is, just before the homecoming game. Seeing her leaving before the final play of the game, Austin stands up to his father and runs after Sam. He apologizes, and they share their first kiss in the rain as the drought suddenly ends.Samantha "Sam" Montgomery is raised by her widowed father Hal, who runs a diner in the San Fernando Valley. Hal later dies in the 1994 Northridge earthquake apparently without leaving a will, leading Sam's vain and greedy stepmother Fiona to inherit everything. Eight years later, 17-year-old Sam is tormented by Fiona and her twin daughters/step-sisters Brianna and Gabriella, while the community faces a drought. Sam and her best friend Carter, an aspiring actor, are bullied by the popular clique at school, led by head cheerleader Shelby. Forced to work at the diner to save money to attend Princeton, Sam is looked after by longtime manager Rhonda, and confides in her online pen pal "Nomad", who shares her dream to attend Princeton to become a writer. Unbeknownst to Sam, "Nomad" is Austin Ames, the popular but unhappy school quarterback and Shelby’s boyfriend, whose father expects him to attend the University of Southern California.
          
          Sam agrees to meet "Nomad" at the school Halloween dance, and Austin breaks up with Shelby. Fiona refuses to give Sam the night off to attend the dance, but Rhonda and Carter intervene, and Rhonda gives Sam a mask and wedding dress to wear as "Cinderella". Dressed as "Prince Charming", Austin reveals to Sam that he is "Nomad" but does not recognize her under her mask, and they share a romantic dance. A masked Carter makes out with Shelby after defending her from the unwanted advances of Austin’s friend, but is forced to drive Sam back to the diner before Fiona discovers she is gone. As they leave, Sam drops her cell phone, which is found by Austin, as he and the missing Cinderella are named homecoming prince and princess. The diner staff stall Fiona and her daughters, and Sam arrives just in time, thankfully avoiding having Fiona come into the kitchen to confront her as she was still wearing the dress under her normal clothes.
          
          The next day, Austin covers the school in flyers, hoping to identify the mysterious Cinderella, and Carter is cruelly rejected by Shelby. Austin’s friends present him with a crowd of girls claiming to be Cinderella, without success. He is accepted to Princeton but unable to tell his father, and visits the diner, where Sam tries to tell him the truth. Brianna and Gabriella discover Sam’s emails with Austin, realizing she is the mystery homecoming princess. After failing to convince Austin that they are each Cinderella, the twins present the emails to Shelby, convincing her that Sam schemed to steal Austin away from her. At the school pep rally, Shelby and the twins perform a humiliating skit exposing Sam as Cinderella, and she goes home in tears.
          
          Having intercepted Sam’s acceptance letter from Princeton, Fiona forges a rejection and feigns sympathy, telling Sam she has a job at the diner for life. Rhonda encourages Sam not to lose hope, and her stepsisters inadvertently uncover a wallpapered-over mural of Hal’s motto. Inspired, Sam finally stands up to Fiona and quits the diner, leading Rhonda, the rest of the staff, and even the customers to leave as well. Moving in with Rhonda, Sam confronts Austin for being afraid to show who he really is, just before the homecoming game. Seeing her leaving before the final play of the game, Austin stands up to his father and runs after Sam. He apologizes, and they share their first kiss in the rain as the drought suddenly ends."""),
              ),
              ),
          )
        ],
      ),
    );
  }
}